---
- name: Installing Apache 
  become: True
  hosts: webserver

  tasks:
  - name: Installing Httpd using yum module
    yum:
     name: httpd
     state: installed

  - name: Starting the service   
    service:
     name: httpd
     state: started
